### ISSUE TITLE
Missing Phage Waits

### ISSUE THREAD

**Issue by acwaits** [scresawn/phamerator#24]
Hello! I am trying to analyze my phage (Waits) and I am not seeing it here on the website. I am having trouble accessing the Linux version and the other 6 phages I am comparing mine to are already available on the website (A15).

Thanks, 
Audrey Waits

**Comment by scresawn** [comment]
Hi Audrey! Waits is in the queue for phamerator.org and should appear on the site within the next few days. I'll close this issue when that happens so that you will get an email about it.

**Comment by scresawn** [comment]
Phage Waits is now available on phamerator.org.
