### ISSUE TITLE
Turn off boxes following mouse arrow

### ISSUE THREAD

**Issue by evozoa** [scresawn/phamerator#29]
When you click on a gene it provides a nucletide fasta, but after a few clicks it seems to stop working. Maybe turning off the floating boxes will rectify this. Personally, I would prefer that this information be presented upon mouse click, rather than appearing on hover.

**Comment by scresawn** [comment]
I'm having trouble reproducing this issue. Can you please find me this morning before you leave so that we can look at it together?

**Comment by scresawn** [comment]
We have recently done away with gene tooltips, at least for now, and we also fixed a bug associated with repeated closing and reopening of dialog boxes resulting in them eventually being unwilling to open.
