### ISSUE TITLE
"No data sets available"

### ISSUE THREAD

**Issue by cem421** [scresawn/phamerator#40]
I created a Phamerator account two weeks ago and have since verified my email and still have no access to data. I receive a message "no preferredDataset dataset defined" when I log in and "No data sets available" from the drop down menu in the upper left corner of the home screen. Nothing appears under the "Genome Maps" section either. This problem is happening to four people in my class, including myself, while working for others.

**Comment by scresawn** [comment]
I have granted you access to the "Actino_Draft" database. Please reload the site and try again. I'd appreciate if you can report back here on whether everything now looks ok. Thanks.

**Comment by cem421** [comment]
Just reloaded it and everything looks good. The three other students who are having the same issue are krv221, brg321, and goc221. If you could possibly look into their accounts as well that would be greatly appreciated. Thank you!

**Comment by scresawn** [comment]
I was able to figure out who they were and attempted to correct theirs at the same time as yours. I hope that worked also.

**Comment by krv221** [comment]
My account is now working. Thank you for your help!
